repos:
- repo: https://github.com/biomejs/pre-commit
  rev: "v0.3.0"  # Use the sha / tag you want to point at
  hooks:
  - id: biome-ci
    additional_dependencies: ["@biomejs/biome@1.4.1"]
- repo: https://github.com/doublify/pre-commit-rust
  rev: "v1.0"
  hooks:
  - id: fmt
  - id: cargo-check
