//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::notes::Entity as Notes;
pub use super::records::Entity as Records;
pub use super::users::Entity as Users;
pub use super::wmus::Entity as Wmus;
