//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "records")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: Option<Date>,
    pub user_id: i32,
    pub wmu_id: i32,
    pub project: Option<String>,
    pub task: Option<String>,
    pub time_charge: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub time: Option<i32>,
    pub mileage: Option<i32>,
    pub mileage_chargable: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::wmus::Entity",
        from = "Column::WmuId",
        to = "super::wmus::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wmus,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::wmus::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wmus.def()
    }
}
